### ISSUE TITLE
Todo for Hidenori

### ISSUE THREAD

**Issue by hfu** [unvt/washi#24]
- [x] Add **issues** based on the internal 2020-09-10 session.
- [x] Complete `sh2` part of `washi`.
- [x] Work on `durana` (phase 2).
